name: 为海思Hi3798MV100编译佳能MF4452驱动（修复ARMHF源）

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 检查源码
        uses: actions/checkout@v4

      - name: 配置ARMHF架构及修正APT源（解决404错误）
        run: |
          # 启用ARMHF架构
          sudo dpkg --add-architecture armhf
          
          # 修正APT源：添加支持ARMHF的主源（替代仅依赖security源）
          # 备份原有源列表
          sudo cp /etc/apt/sources.list /etc/apt/sources.list.bak
          # 覆盖源列表，确保包含ARMHF架构的正确路径
          sudo tee /etc/apt/sources.list << EOF
          deb [arch=amd64,armhf] http://archive.ubuntu.com/ubuntu jammy main universe restricted multiverse
          deb [arch=amd64,armhf] http://archive.ubuntu.com/ubuntu jammy-updates main universe restricted multiverse
          deb [arch=amd64,armhf] http://archive.ubuntu.com/ubuntu jammy-backports main universe restricted multiverse
          deb [arch=amd64,armhf] http://security.ubuntu.com/ubuntu jammy-security main universe restricted multiverse
          EOF
          
          # 强制更新源列表（忽略无效索引）
          sudo apt-get update -qq || true

      - name: 安装编译依赖（ARMHF库）
        run: |
          sudo apt-get install -y --no-install-recommends \
            build-essential crossbuild-essential-armhf \
            libcups2:armhf libcups2-dev:armhf \
            libusb-1.0-0:armhf libusb-1.0-0-dev:armhf \
            zlib1g:armhf zlib1g-dev:armhf \
            pkg-config dpkg-dev fakeroot wget tar unzip

      - name: 下载海思Hi3798MV100工具链
        run: |
          wget -O hisiv500-toolchain.tar.gz https://github.com/link?target=https%3A%2F%2Freleases.example.com%2Farm-hisiv500-linux.tar.gz \
            --user-agent="Mozilla/5.0" --no-check-certificate
          sudo mkdir -p /opt/arm-hisiv500-linux
          sudo tar xzf hisiv500-toolchain.tar.gz -C /opt/arm-hisiv500-linux --strip-components=1
          if [ ! -f "/opt/arm-hisiv500-linux/bin/arm-hisiv500-linux-gcc" ]; then
            echo "工具链解压失败，请检查链接"
            exit 1
          fi

      - name: 配置工具链环境变量
        run: |
          echo 'export PATH=/opt/arm-hisiv500-linux/bin:$PATH' >> $GITHUB_ENV
          echo 'export CC=arm-hisiv500-linux-gcc' >> $GITHUB_ENV
          echo 'export CXX=arm-hisiv500-linux-g++' >> $GITHUB_ENV
          echo 'export AR=arm-hisiv500-linux-ar' >> $GITHUB_ENV
          echo 'export LDFLAGS="-L/opt/arm-hisiv500-linux/arm-hisiv500-linux/libc/lib"' >> $GITHUB_ENV

      - name: 下载佳能cndrvcups-lb驱动源码
        run: |
          wget -O cndrvcups-lb.tar.gz https://gdlp01.c-wss.com/gds/8/0100010348/01/cndrvcups-lb-2.70-1.tar.gz
          tar xzf cndrvcups-lb.tar.gz
          mv cndrvcups-lb-2.70-1 cndrvcups-lb-src

      - name: 调整源码适配Hi3798MV100
        run: |
          cd cndrvcups-lb-src
          sed -i 's/-std=c++11/-std=c++0x/g' configure
          sed -i "s|^CPPFLAGS=|CPPFLAGS=-I/opt/arm-hisiv500-linux/arm-hisiv500-linux/libc/include |g" configure

      - name: 配置编译参数
        run: |
          cd cndrvcups-lb-src
          ./configure \
            --host=arm-hisiv500-linux \
            --prefix=/usr \
            --libdir=/usr/lib/arm-linux-gnueabihf \
            --sysconfdir=/etc \
            --with-cupsfilterdir=/usr/lib/cups/filter \
            --with-cupsppddir=/usr/share/cups/model \
            --enable-ufr2 \
            --disable-shared

      - name: 编译驱动
        run: |
          cd cndrvcups-lb-src
          make -j$(nproc)
          if [ ! -f "src/cups/filter/cndrvcups-lb" ]; then
            echo "编译失败，未生成关键文件"
            exit 1
          fi

      - name: 打包为ARMHF Deb包
        run: |
          cd cndrvcups-lb-src
          mkdir -p debian/DEBIAN
          cat > debian/DEBIAN/control << EOF
          Package: cndrvcups-lb-mf4452
          Version: 2.70-1
          Architecture: armhf
          Maintainer: YourName <your@email.com>
          Depends: libcups2 (>= 2.3), libusb-1.0-0 (>= 1.0.23), zlib1g (>= 1:1.2.11)
          Description: Canon MF4452 printer driver for Hi3798MV100 (ARMHF)
          EOF
          mkdir -p debian/usr/lib/cups/filter
          cp src/cups/filter/cndrvcups-lb debian/usr/lib/cups/filter/
          mkdir -p debian/usr/share/cups/model
          cp ppd/*.ppd.gz debian/usr/share/cups/model/
          fakeroot dpkg-deb --build debian ../cndrvcups-lb-hi3798mv100_2.70-1_armhf.deb

      - name: 上传编译结果
        uses: actions/upload-artifact@v4
        with:
          name: cndrvcups-lb-hi3798mv100-armhf
          path: cndrvcups-lb-hi3798mv100_2.70-1_armhf.deb
