name: 为海思Hi3798MV100（ARMHF）编译佳能MF4452驱动

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: 更新系统与依赖
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            build-essential crossbuild-essential-armhf \
            libcups2-dev:armhf libusb-1.0-0-dev:armhf zlib1g-dev:armhf \
            pkg-config dpkg-dev fakeroot wget tar unzip

      - name: 下载Hi3798MV100专用工具链（arm-hisiv500-linux）
        run: |
          # Hi3798MV100通常使用hisiv500工具链（海思官方适配）
          # 若链接失效，从海思SDK获取：Hi3798MV100 SDK中的osdrv/toolchain目录
          wget -O hisiv500-toolchain.tar.gz https://github.com/link?target=https%3A%2F%2Freleases.example.com%2Fhisiv500-toolchain.tar.gz \
            --user-agent="Mozilla/5.0" --no-check-certificate
          # 解压到/opt目录（工具链典型路径）
          sudo mkdir -p /opt/arm-hisiv500-linux
          sudo tar xzf hisiv500-toolchain.tar.gz -C /opt/arm-hisiv500-linux --strip-components=1
          # 验证工具链是否存在
          ls -ld /opt/arm-hisiv500-linux/bin/arm-hisiv500-linux-gcc

      - name: 配置工具链环境变量
        run: |
          echo 'export PATH=/opt/arm-hisiv500-linux/bin:$PATH' >> $GITHUB_ENV
          echo 'export CC=arm-hisiv500-linux-gcc' >> $GITHUB_ENV
          echo 'export CXX=arm-hisiv500-linux-g++' >> $GITHUB_ENV
          echo 'export AR=arm-hisiv500-linux-ar' >> $GITHUB_ENV

      - name: 下载佳能MF4452驱动源码（cndrvcups-lb）
        run: |
          # 佳能官方最新稳定版（支持MF4452的UF2协议）
          wget -O cndrvcups-lb.tar.gz https://gdlp01.c-wss.com/gds/8/0100010348/01/cndrvcups-lb-2.70-1.tar.gz
          tar xzf cndrvcups-lb.tar.gz
          mv cndrvcups-lb-2.70-1 cndrvcups-lb-src  # 统一目录名

      - name: 调整源码适配Hi3798MV100（ARMHF）
        run: |
          cd cndrvcups-lb-src
          # 解决可能的glibc版本兼容问题（Hi3798MV100系统可能用较旧glibc）
          sed -i 's/-std=c++11/-std=c++0x/g' configure  # 降级C++标准
          # 强制使用交叉编译工具链的库
          export LDFLAGS="-L/opt/arm-hisiv500-linux/arm-hisiv500-linux/libc/lib"

      - name: 配置编译参数（针对CUPS和Hi3798MV100）
        run: |
          cd cndrvcups-lb-src
          ./configure \
            --host=arm-hisiv500-linux \  # 匹配工具链前缀
            --prefix=/usr \
            --libdir=/usr/lib/arm-linux-gnueabihf \  # Hi3798MV100的库路径
            --sysconfdir=/etc \
            --with-cupsfilterdir=/usr/lib/cups/filter \  # CUPS过滤器路径
            --with-cupsppddir=/usr/share/cups/model \  # PPD文件路径
            --enable-ufr2 \  # 必须启用，MF4452依赖UF2协议
            --disable-shared  # 静态编译减少依赖问题

      - name: 编译驱动
        run: |
          cd cndrvcups-lb-src
          make -j$(nproc)  # 多线程加速编译

      - name: 打包为ARMHF架构Deb包
        run: |
          cd cndrvcups-lb-src
          fakeroot dpkg-deb --build . ../cndrvcups-lb-hi3798mv100_armhf.deb

      - name: 上传编译结果
        uses: actions/upload-artifact@v3
        with:
          name: cndrvcups-lb-mf4452-hi3798mv100
          path: cndrvcups-lb-hi3798mv100_armhf.deb

      - name: 验证Deb包架构
        run: |
          dpkg-deb --info cndrvcups-lb-hi3798mv100_armhf.deb | grep Architecture  # 应显示armhf
