name: Compile ARMHF Driver for Canon MF4452

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          autoconf \
          libtool \
          pkg-config \
          libcups2-dev \
          libusb-1.0-0-dev \
          libxml2-dev \
          libjpeg-dev \
          libtiff-dev \
          git \
          cmake \
          crossbuild-essential-armhf \
          qemu-user-static

    - name: Set ARMHF Environment
      run: |
        echo "CC=arm-linux-gnueabihf-gcc" >> $GITHUB_ENV
        echo "CXX=arm-linux-gnueabihf-g++" >> $GITHUB_ENV
        echo "CFLAGS=-march=armv7-a -mtune=cortex-a9 -mfpu=neon -mfloat-abi=hard" >> $GITHUB_ENV
        echo "CXXFLAGS=$CFLAGS" >> $GITHUB_ENV

    - name: Build Dependency Library
      run: |
        cd libs/cnacom
        make clean
        make ARCH=armhf
        sudo cp libcnacbcom.so /usr/lib/arm-linux-gnueabihf/

    - name: Configure Project
      run: |
        ./autogen.sh
        ./configure \
          --prefix=/usr \
          --host=arm-linux-gnueabihf \
          CC=${{ env.CC }} \
          CXX=${{ env.CXX }} \
          CFLAGS="${{ env.CFLAGS }}" \
          CXXFLAGS="${{ env.CXXFLAGS }}"

    - name: Compile Driver
      run: make -j$(nproc)

    - name: Package Artifacts
      run: |
        mkdir -p ./artifacts
        cp -r ./src/*.so ./artifacts/
        cp ./cndrvcups-lb.ppd ./artifacts/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: armhf-driver
        path: ./artifacts/*
